### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/openapi-sampler#3]
Version 1.0.0-beta1

I believe related to the new resolution of `$ref`s and circular references. I wasn't able to produce an artificial test-case which generated the error though.

Test-case (requires patientview API file from openapi-directory):

```js
let util = require('util');
let fs = require('fs');
let sampler = require('openapi-sampler');
let yaml = require('js-yaml');

let apiStr = fs.readFileSync('../openapi-directory/APIs/patientview.org/1.0/swagger.yaml','utf8');
let api = yaml.safeLoad(apiStr,{json:true});

let schema = api.definitions.Group;

let sample = sampler.sample(schema,{},api);

console.log(util.inspect(sample));
```

**Comment by MikeRalphson** [comment]
Thanks!

**Comment by RomanGotsiy** [comment]
@MikeRalphson thanks you! Now, after it's tested on the collection, I can be sure it won't fail on any spec 👍
